wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
amsgrad:
  desc: null
  value: true
architecture:
  desc: null
  value: vgg16_architecture_3
batch_size:
  desc: null
  value: 90
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0005
trainable:
  desc: null
  value: true
