wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
architecture:
  desc: null
  value: attention_architecture_1
batch_size:
  desc: null
  value: 90
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0005
